# Generated by Django 6.1.1 on 2026-10-03 04:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(verbose_name='课时编号')),
                ('title', models.CharField(max_length=200, verbose_name='课时标题')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='课时副标题')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='预计时长(分钟)')),
                ('difficulty', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级')], default='beginner', max_length=20, verbose_name='难度')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '课时',
                'verbose_name_plural': '课时',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='模块标题')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='副标题')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标类名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '课程模块',
                'verbose_name_plural': '课程模块',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='章节标题')),
                ('content', models.TextField(blank=True, verbose_name='内容(Markdown)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('content_type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('video', '视频')], default='text', max_length=20, verbose_name='内容类型')),
                ('video_url', models.URLField(blank=True, max_length=500, verbose_name='视频URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.lesson', verbose_name='所属课时')),
            ],
            options={
                'verbose_name': '课时章节',
                'verbose_name_plural': '课时章节',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='所属模块'),
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField(verbose_name='页码')),
                ('image', models.ImageField(upload_to='courses/pages/', verbose_name='页面图片')),
                ('thumbnail', models.ImageField(blank=True, upload_to='courses/thumbnails/', verbose_name='缩略图')),
                ('raw_text', models.TextField(blank=True, verbose_name='提取的文本(用于搜索)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='courses.lesson', verbose_name='所属课时')),
            ],
            options={
                'verbose_name': '内容页面',
                'verbose_name_plural': '内容页面',
                'ordering': ['lesson', 'page_number'],
                'unique_together': {('lesson', 'page_number')},
            },
        ),
    ]
