export const guidanceCopy = {
  en: {
    title: 'Mounting-point guide', locate: 'Locate mounting point', allTargets: 'All mounting points',
    currentTargets: 'Current step + selected mounting point', display: 'View options',
    start: 'Start: locate the main frame', resume: 'Locate the next part',
    advanced: 'Advanced: position & rotation', map: 'Mounting map · top view',
    mapHint: 'Choose a marker to select a part. This does not install it.',
    front: 'FRONT / NOSE', rear: 'REAR', left: 'LEFT', right: 'RIGHT', center: 'CENTER',
    datum: 'Teaching layout · assumed positions', target: 'Target position',
    stages: ['Find mounting point', 'Align position & direction', 'Confirm installation'],
    next: 'Next part', prerequisites: 'Install these first',
    position: 'Position', angle: 'Direction', within: 'Within tolerance', outside: 'Needs alignment',
    limit: 'limit', committed: 'Compared with the last committed transform; updates when a drag ends.',
    status: {
      installed: 'Installed at the target', inspection: 'Inspection only — return to assembly view',
      invalid: 'Invalid transform — reset position & direction', blocked: 'Waiting for prerequisite parts', move: 'Move to the highlighted mounting point',
      rotate: 'Position is ready — align the direction', scale: 'Scale does not match the target',
      ready: 'Aligned — ready to check & install',
    },
    alignHint: 'Drag the part or use Align to target as teaching assistance. Installation still requires confirmation.',
    readyHint: 'Position and direction are within tolerance. Press Check & install to confirm.',
    blockedHint: 'You can inspect this target now. Install the required parts before confirming.',
    scaleHint: 'Scale is outside the teaching target. Align to target restores the assumed transform.',
    invalidHint: 'Reset the position and direction with Align to target before trying to install.',
    installedHint: 'This part is locked. Select the next part, or disassemble it to practise.',
  },
  zh: {
    title: '安装位指南', locate: '定位安装位', allTargets: '全部安装位',
    currentTargets: '当前步骤 + 选中零件安装位', display: '显示选项',
    start: '开始：定位主机架', resume: '定位下一零件',
    advanced: '高级调整：位置与旋转', map: '安装位导航 · 俯视',
    mapHint: '点击标记只选择零件，不会自动安装。',
    front: '机头 / 前', rear: '机尾 / 后', left: '左', right: '右', center: '中央',
    datum: '教学示意 · 假设安装位', target: '目标位置',
    stages: ['找安装位', '对齐位置与方向', '确认安装'],
    next: '下一零件', prerequisites: '先安装这些零件',
    position: '位置', angle: '方向', within: '容差内', outside: '需要对齐',
    limit: '容差', committed: '与已提交变换比较；拖动结束后更新。',
    status: {
      installed: '已安装到目标位', inspection: '仅供观察，请返回装配视图',
      invalid: '变换无效，请重置位置与方向', blocked: '等待前置零件安装', move: '移动到高亮安装位',
      rotate: '位置已对齐，继续调整方向', scale: '缩放与安装位不一致',
      ready: '已对齐，可以检查并安装',
    },
    alignHint: '拖动零件，或使用“对齐安装位置”教学辅助；安装仍须单独确认。',
    readyHint: '位置和方向均在容差内，请点击“检查并安装”确认。',
    blockedHint: '现在可以观察安装位；确认安装前，请先完成所需零件。',
    scaleHint: '缩放与教学目标不符；对齐安装位置可恢复假设变换。',
    invalidHint: '请使用“对齐安装位置”重置位置与方向，再检查安装。',
    installedHint: '此零件已锁定。选择下一零件，或拆卸后练习。',
  },
};
