export const guidanceCopy = {
  en: {
    title: 'Mounting-point guide', locate: 'Locate mounting point', allTargets: 'All mounting points',
    currentTargets: 'Current step + selected mounting point', display: 'View options',
    start: 'Start: locate the main frame', resume: 'Locate the next part',
    advanced: 'Advanced: position & rotation', map: 'Mounting map · top view',
    mapHint: 'Choose a marker to select a part. This does not install it.',
    front: 'FRONT / NOSE', rear: 'REAR', left: 'LEFT', right: 'RIGHT', center: 'CENTER',
    datum: 'Teaching layout · assumed positions', target: 'Target position',
    stages: ['Find mounting point', 'Move close to target', 'Release to snap'],
    next: 'Next part', prerequisites: 'Install these first',
    position: 'Position', angle: 'Direction', within: 'Within capture range', outside: 'Move closer',
    limit: 'snap range', committed: 'Compared with the last committed transform; updates when a drag ends.',
    status: {
      installed: 'Snapped precisely into place and installed', inspection: 'Inspection only — return to assembly view',
      invalid: 'Invalid transform — reset position & direction', blocked: 'Waiting for prerequisite parts', move: 'Move to the highlighted mounting point',
      rotate: 'Position is ready — align the direction', scale: 'Scale does not match the target',
      ready: 'Release to snap & install automatically',
    },
    alignHint: 'Drag within the capture range and release. Position and orientation snap automatically. Or use Snap into place for one-click assistance.',
    readyHint: 'Release the drag to snap and install. A previously loose part at this position can be dragged slightly and released again.',
    blockedHint: 'Install the prerequisites first. A blocked part remains loose even inside the capture range.',
    scaleHint: 'Scale does not match the target. Snap into place restores the assumed transform.',
    invalidHint: 'Use Snap into place to restore a valid target transform.',
    installedHint: 'This part is locked. Select the next part, or disassemble it to practise.',
  },
  zh: {
    title: '安装位指南', locate: '定位安装位', allTargets: '全部安装位',
    currentTargets: '当前步骤 + 选中零件安装位', display: '显示选项',
    start: '开始：定位主机架', resume: '定位下一零件',
    advanced: '高级调整：位置与旋转', map: '安装位导航 · 俯视',
    mapHint: '点击标记只选择零件，不会自动安装。',
    front: '机头 / 前', rear: '机尾 / 后', left: '左', right: '右', center: '中央',
    datum: '教学示意 · 假设安装位', target: '目标位置',
    stages: ['找安装位', '拖到附近', '松手吸附'],
    next: '下一零件', prerequisites: '先安装这些零件',
    position: '位置', angle: '方向', within: '吸附范围内', outside: '继续靠近',
    limit: '吸附范围', committed: '与已提交变换比较；拖动结束后更新。',
    status: {
      installed: '已精准吸附并安装', inspection: '仅供观察，请返回装配视图',
      invalid: '变换无效，请重置位置与方向', blocked: '等待前置零件安装', move: '移动到高亮安装位',
      rotate: '位置已对齐，继续调整方向', scale: '缩放与安装位不一致',
      ready: '松手后自动吸附安装',
    },
    alignHint: '拖进吸附范围后松手，自动精准定位、校正朝向并安装；也可点“自动吸附到位”辅助。',
    readyHint: '松开拖动即可吸附安装。此前停在此处的散件，轻微拖动后再松手即可。',
    blockedHint: '请先安装列出的前置零件；未满足时，即使靠近安装位也不会吸附。',
    scaleHint: '缩放与教学目标不符；“自动吸附到位”可恢复目标变换。',
    invalidHint: '请使用“自动吸附到位”恢复有效的目标位置与方向。',
    installedHint: '此零件已锁定。选择下一零件，或拆卸后练习。',
  },
};
