import type { AssemblyErrorCode, PartCategory } from '../contracts';
export type Language = 'en' | 'zh';
export const strings = {
  en: {
    offlineReady: 'Offline ready', offlinePreparing: 'Preparing offline cache…', title: 'Assembly Studio', subtitle: 'DRONE LAB / LOCAL WORKBENCH', local: 'Local', library: 'Part library', search: 'Search parts or IDs…', all: 'All parts', pieces: 'parts', assembled: 'installed', scattered: 'Loose', installed: 'Installed', guided: 'Guided assembly', free: 'Free assembly', move: 'Move', rotate: 'Rotate', undo: 'Undo', reset: 'Reset', resetTitle: 'Reset the workbench?', resetBody: 'All components return to their starting positions. You can undo this reset.', cancel: 'Cancel', confirmReset: 'Reset workbench', exploded: 'Exploded view', normal: 'Assembly view', perspective: 'Perspective', top: 'Top', front: 'Front', side: 'Side', workflow: 'Assembly guide', step: 'Step', complete: 'Assembly complete', completeText: 'All 17 components are installed. Inspect the assembly or try disassembly.', select: 'Select a part to begin', selectHint: 'Click a component in the scene or the part library.', selected: 'Selected part', transform: 'Transform', position: 'Position · teaching units', rotation: 'Rotation · degrees', apply: 'Apply transform', align: 'Align to target', install: 'Check & install', remove: 'Disassemble', feedback: 'Installation feedback', ready: 'Ready for assembly', readyText: 'Select a component, place it at its target, then check installation.', aligned: 'Aligned to the teaching target. Check & install to confirm.', moved: 'Transform updated.', removed: 'Component removed. It can now be moved.', checked: 'Installation confirmed.', progress: 'Assembly progress', remaining: 'remaining', saved: 'Saved on this device', restored: 'Progress restored', saveError: 'Saving unavailable — keep this tab open', invalidSave: 'Saved data was incompatible. A fresh workbench is ready.', unavailableSave: 'Storage unavailable. Progress will not survive refresh.', started: 'New workbench', ghost: 'Outlines & labels: current step and selected target', orbit: 'Empty space: left-drag to orbit · Scroll: zoom · Right-drag: pan', lock: 'Installed components are locked. Disassemble to move them.', explosionLock: 'Exploded view is for inspection. Return to assembly view to edit.', freeHint: 'Explore your own order. Prerequisites and installation tolerances still apply.', reference: 'Component references', noMatch: 'No matching parts', unitHint: 'Assumed layout · not physical dimensions', showTarget: 'Target assistance', continue: 'Select next part', rendererError: '3D scene could not start', fpsWaiting: 'Measuring FPS…', preview: 'Preview', errorDistance: 'Position error', errorAngle: 'Angle error', required: 'Related components', inspect: 'Inspect', resetDone: 'Workbench reset. Undo is available.', undoDone: 'Previous assembly action restored.', pending: 'Integration preview', history: 'actions available to undo',
  },
  zh: {
    offlineReady: '离线缓存已就绪', offlinePreparing: '正在准备离线缓存…', title: '无人机组装工作台', subtitle: '无人机教学 / 本地工作台', local: '本地', library: '零件库', search: '搜索零件或编号…', all: '全部零件', pieces: '件零件', assembled: '已安装', scattered: '散件', installed: '已安装', guided: '引导组装', free: '自由组装', move: '移动', rotate: '旋转', undo: '撤销', reset: '重置', resetTitle: '重置工作台？', resetBody: '所有零件回到初始散件位置。重置后仍可撤销。', cancel: '取消', confirmReset: '重置工作台', exploded: '爆炸图', normal: '装配视图', perspective: '透视', top: '俯视', front: '正视', side: '侧视', workflow: '组装步骤', step: '步骤', complete: '组装完成', completeText: '全部 17 个零件已安装。可以检查整机或练习拆卸。', select: '选择一个零件开始', selectHint: '点击场景中的零件或左侧零件库。', selected: '当前零件', transform: '变换调整', position: '位置 · 教学单位', rotation: '旋转 · 度', apply: '应用位置与旋转', align: '对齐安装位置', install: '检查并安装', remove: '拆卸', feedback: '安装反馈', ready: '等待组装', readyText: '选择零件，将其放到目标位置，然后检查安装。', aligned: '已对齐教学安装位，请点击“检查并安装”确认。', moved: '位置与旋转已更新。', removed: '零件已拆卸，现在可以移动。', checked: '安装检查通过。', progress: '组装进度', remaining: '件待安装', saved: '已保存在此设备', restored: '进度已恢复', saveError: '保存不可用，请保持页面打开', invalidSave: '保存数据不兼容，已打开新工作台。', unavailableSave: '存储不可用，刷新后进度无法保留。', started: '新工作台', ghost: '轮廓与标签：当前步骤及选中件安装位', orbit: '空白处左键拖动：环绕 · 滚轮：缩放 · 右键拖动：平移', lock: '已安装零件锁定，拆卸后才能移动。', explosionLock: '爆炸图用于观察，返回装配视图后才能编辑。', freeHint: '自由探索安装顺序，前置零件与安装容差仍会检查。', reference: '部件参考文件', noMatch: '没有匹配的零件', unitHint: '假设布局 · 非真实尺寸', showTarget: '安装位辅助', continue: '选择下一零件', rendererError: '3D 场景未能启动', fpsWaiting: '正在测量帧率…', preview: '预览', errorDistance: '位置误差', errorAngle: '角度误差', required: '相关零件', inspect: '观察', resetDone: '工作台已重置，可撤销。', undoDone: '已恢复上一装配操作。', pending: '集成预览', history: '个操作可撤销',
  },
};
export const categoryNames: Record<Language, Record<PartCategory,string>> = {
  en: {frame:'Frame', 'landing-gear':'Landing gear', power:'Power', propeller:'Propellers', guard:'Guards', control:'Controller', battery:'Battery'},
  zh: {frame:'机架', 'landing-gear':'起落架', power:'动力组件', propeller:'桨叶', guard:'保护架', control:'控制模块', battery:'电池'},
};
export const errorMessages: Record<Language, Record<AssemblyErrorCode,string>> = {
  en: {OK:'Check passed.', UNKNOWN_PART:'This component ID is unknown.', ALREADY_INSTALLED:'This component is already installed.', NOT_INSTALLED:'This component is not installed.', MISSING_PREREQUISITES:'Install the required components first.', POSITION_OUT_OF_TOLERANCE:'Position is outside the installation tolerance.', ANGLE_OUT_OF_TOLERANCE:'Orientation is outside the installation tolerance.', SCALE_MISMATCH:'Scale does not match the teaching target.', DEPENDENTS_INSTALLED:'Remove the dependent components first.', INVALID_TRANSFORM:'The transform contains invalid values.', PART_LOCKED:'Disassemble this component before moving it.', EXPLODED_VIEW_ACTIVE:'Return to assembly view before editing.', NOTHING_TO_UNDO:'There is no assembly action to undo.'},
  zh: {OK:'检查通过。', UNKNOWN_PART:'零件编号不存在。', ALREADY_INSTALLED:'该零件已经安装。', NOT_INSTALLED:'该零件尚未安装。', MISSING_PREREQUISITES:'请先安装前置零件。', POSITION_OUT_OF_TOLERANCE:'位置超出安装容差。', ANGLE_OUT_OF_TOLERANCE:'朝向超出安装角度容差。', SCALE_MISMATCH:'缩放与教学安装位不一致。', DEPENDENTS_INSTALLED:'请先拆卸依赖于它的零件。', INVALID_TRANSFORM:'位置、旋转或缩放数值无效。', PART_LOCKED:'请先拆卸该零件再移动。', EXPLODED_VIEW_ACTIVE:'请返回装配视图后编辑。', NOTHING_TO_UNDO:'没有可撤销的装配操作。'},
};
